from imports import *

janela = Tk()
janela.title('Calculadora Primos Depósito')
janela.geometry('490x560+500+80')
photo = PhotoImage(file = 'assets//icon.png')
janela.wm_iconphoto(False, photo)
janela.resizable(0, 0)

img_bg_main = PhotoImage(file='assets//img_bg_main.png')
img_bg_forro = PhotoImage(file='assets//img_bg_forro.png')
img_bg_laje = PhotoImage(file='assets//img_bg_laje.png')
img_bg_forro = PhotoImage(file='assets//img_bg_forro.png')
img_bg_opcao_laje = PhotoImage(file='assets//img_bg_opcao_laje.png')
img_bg_area_laje = PhotoImage(file='assets//img_bg_area_laje.png')
img_button_calcular_forro = PhotoImage(file='assets//button_calcular_forro.png')
img_button_calcular_laje = PhotoImage(file='assets//button_calcular_laje.png')
img_button_tenho_trilho = PhotoImage(file='assets//button_tenho_trilho.png')
img_button_nao_tenho_trilho = PhotoImage(file='assets//button_nao_tenho_trilho.png')
img_button_calcular = PhotoImage(file='assets//button_calcular.png')
img_button_back = PhotoImage(file='assets//button_back.png')
img_button_info = PhotoImage(file='assets//button_info.png')
img_button_trilho_comprimento = PhotoImage(file='assets//button_trilho_comprimento.png')
img_button_trilho_largura = PhotoImage(file='assets//button_trilho_largura.png')

